### PR TITLE
Merge FastJetClustering into MarlinFastJet

### PR DESCRIPTION
**Pull request by andresailer**
Start addressing ilcsoft/FastJetClustering#1

BEGINRELEASENOTES
- Merged the FastJetClustering processor into the MarlinFastJet package
- Fix Warnings in FastJetClustering processor

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
I am very curious to see what will happen with this when rebasing

**Comment by andresailer** [comment]
commands used to get here:
```
git remote add fastjetcluster git@github.com:iLCSoft/FastJetClustering.git
git fetch fastjetcluster
git checkout fastjetcluster/master -b fjcMaster
## remove unnecessary files, move files to different folders if needed
git commit -m"FastJetClustering: remove obsolete files before merging"
git checkout master ## MarlinFastJet master
git checkout -b mergeFJC ## MarlinFastJet Feature branch to receive merge
git merge fjcMaster --allow-unrelated-histories ## merged fjcMaster into mergeFJC
### fix warnings, make FJC compile
git commit ...
```

**Comment by gaede** [comment]
@andresailer can we merge this now ?

**Comment by andresailer** [comment]
Yes

**Review by gaede — APPROVED** [review]
looks ok - will merge.

**Comment by gaede** [comment]
@andresailer: "This branch cannot be rebased due to conflicts"  - and now ?

**Comment by andresailer** [comment]
Thats what I feared. Will directly push to origin after lunch

**Comment by andresailer** [comment]
pushed to master directly

**Pull request merged**
